version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Devdatta@123
      POSTGRES_DB: health_db
    ports:
      - "5432:5432"
    networks:
      - health-network

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - health-network

  backend:
    build: .
    container_name: fastapi_backend
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Devdatta@123@db:5432/health_db
    networks:
      - health-network

  worker:
    build: .
    container_name: celery_worker
    depends_on:
      - backend
      - redis
    command: ["celery", "-A", "app.worker", "worker", "--loglevel=info"]
    networks:
      - health-network

  frontend:
    build:
      context: ./real-time-dashboard
      dockerfile: Dockerfile
    container_name: react_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - health-network

networks:
  health-network:
    driver: bridge

volumes:
  postgres_data: