version: '3.8'
services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Devdatta@123
      POSTGRES_DB: health_db
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: fastapi_backend
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    container_name: celery_worker
    depends_on:
      - backend
      - redis
    command: ["celery", "-A", "app.worker", "worker", "--loglevel=info"]
